#!/usr/bin/env bash

# Initialize stack.
fin project start

# Install particle
fin exec bin/particle.sh "$@"

# Build site
fin exec bin/build.sh "$@"

# Install Drupal site
fin exec bin/install.sh "$@"

# Repeat here just to show the site URL when we are done.
fin project start
